name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint_and_tests:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Run tests
        run: zig build test --summary all
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    needs: [lint_and_tests]
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Build
        run: zig build
